AWSTemplateFormatVersion: 2010-09-09
Description: Build a Cluster Mastster
Parameters:
  InstanceType:
    Description: Instance type to launch EC2 instances.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
  DisableApiTermination:
    Type: String
    Description: >-
      Prevent APIs, including CloudFormation, from being able to delete EC2
      instances
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
  DeleteOnTermination:
    Type: String
    Description: Should EBS volumes be deleted upon instance termination?
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  SplunkSecurityGroup:
    Description: What Security Group do you wish to use
    Type: String
    Default: sg-02173e5e6f2cb45c8
  GoldenImageId:
    Description: Image ID of the Golden Image
    Type: String
    Default: buildgolden-AMI-ID
  IamInstanceProfile:
    Description: What IAM Policy should be applied to these machines
    Type: String
    Default: EC2S3FULL
  KeyName:
    Description: What Key should be used
    Type: String
    Default: awslab
  AssociatePublicIpAddress:
    Type: String
    Description: >-
      Should a Public IP be given to management devices - good for
      troubleshooting
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  AwsS3Bucket:
    Type: String
    Description: Name of the bucket for Splunk install scripts
    Default: ajs-aws-splunk
  SplunkHome:
    Type: String
    Description: Name of the directory to install Splunk
    Default: /opt/splunk
  SplunkSystemUser:
    Type: String
    Description: Name of the user that Splunk is to be installed as
    Default: splunk
  SplunkAdminUser:
    Type: String
    Description: Name of the Splunkadmin user
    Default: admin
  SplunkAdminPassword:
    Type: String
    Description: Splunk Admin user password
    Default: changeme1
  NumberOfAZs:
    Type: String
    Description: Number of Availability Zones
    Default: 3
  IndexClusterLabel:
    Type: String
    Description: Name of the Index Cluster
    Default: idxcluster
  SearchClusterLabel:
    Type: String
    Description: Name of the Index Cluster
    Default: shcluster
  SplunkGeneralSecret:
    Type: String
    Description: Splunk General Secret
    Default: password1
  SplunkClusterSecret:
    Type: String
    Description: Splunk Cluster Secret
    Default: password2
  SplunkIndexDiscoverySecret:
    Type: String
    Description: Splunk Index Discovery Secret
    Default: password3
Resources:
  CM:
    Type: 'AWS::EC2::Instance'
    Properties:
      DisableApiTermination: !Ref DisableApiTermination
      IamInstanceProfile: !Ref IamInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 20
            DeleteOnTermination: !Ref DeleteOnTermination
        - DeviceName: /dev/sdb
          Ebs:
            VolumeType: gp2
            VolumeSize: 20
            DeleteOnTermination: !Ref DeleteOnTermination
      NetworkInterfaces:
        - GroupSet:
            - !Ref SplunkSecurityGroup
          AssociatePublicIpAddress: !Ref AssociatePublicIpAddress
          DeviceIndex: '0'
          DeleteOnTermination: true
      ImageId: >-
        Fn::ImportValue Fn::Sub - ${GoldenImage} - { GoldenImage:!Ref GoldenImageId }
      AvailabilityZone: us-east-2a
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Application
          Value: !Ref 'AWS::StackId'
        - Key: Role
          Value: cluster-master
        - Key: Name
          Value: cluster-master
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -v
          aws s3 cp s3://${AwsS3Bucket}/bash/cm.sh /tmp/cm.sh
          export hostname=cm
          export SPLUNK_HOME=${SplunkHome}
          export AWS_S3_BUCKET=${AwsS3Bucket}
          export SPLUNK_SYSTEM_USER=${SplunkSystemUser}
          export SPLUNK_ADMIN_USER=${SplunkAdminUser}
          export SPLUNK_ADMIN_PASSWORD=${SplunkAdminPassword}
          export SPLUNK_GENERAL_SECRET=${SplunkGeneralSecret}
          export SPLUNK_CLUSTER_SECRET=${SplunkClusterSecret}
          export SPLUNK_INDEX_DISCOVERY_SECRET=${SplunkIndexDiscoverySecret}
          export NumberOfAZs=${NumberOfAZs}
          export INDEX_CLUSTER_LABEL=${IndexClusterLabel}
          export SEARCH_CLUSTER_LABEL=${SearchClusterLabel}
          chmod 755 /tmp/cm.sh
          sudo -E /tmp/cm.sh
          rm -f /tmp/cm.sh
